### ISSUE TITLE
Getting errors trying to run LESS styles.

### ISSUE THREAD

**Issue by mikebronner** [ingrammicro/puzzle-tokens#2]
```
Started
Read LESS: running...
/usr/local/lib/node_modules/less
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/less'
Require stack:
- /private/var/folders/k8/vy_1t24s075cnqhjpy2f6qx80000gn/T/nsconvert_less.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at transformLESStoJSON (/private/var/folders/k8/vy_1t24s075cnqhjpy2f6qx80000gn/T/nsconvert_less.js:96:16)
    at Object.<anonymous> (/private/var/folders/k8/vy_1t24s075cnqhjpy2f6qx80000gn/T/nsconvert_less.js:27:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/private/var/folders/k8/vy_1t24s075cnqhjpy2f6qx80000gn/T/nsconvert_less.js'
  ]
}
```

Less is installed:
```
which less
/usr/bin/less
```

Any suggestions? Thanks!

**Comment by mikebronner** [comment]
I had to run the full install command:
```
npm install global less
```

After that it worked.
