### ISSUE TITLE
TypeError, plugin not working through the CLI anymore

### ISSUE THREAD

**Issue by vkoopmans-resoluut** [ingrammicro/puzzle-tokens#51]
PROCESS /Users/vincentk/Versions/ConnectApp/connect_app_atomic_library-vm.sketch
 APPLY STYLES...
TypeError: undefined is not an object (evaluating 'this.pathToSource.substring')
    at run (/Users/vincentk/Library/Application Support/com.bohemiancoding.sketch3/Plugins/PuzzleTokens.sketchplugin/Contents/Sketch/cmdline-functions.js:2007:52)
    at runFromCmd (/Users/vincentk/Library/Application Support/com.bohemiancoding.sketch3/Plugins/PuzzleTokens.sketchplugin/Contents/Sketch/cmdline-functions.js:1979:33)
    at applyStyles (/Users/vincentk/Library/Application Support/com.bohemiancoding.sketch3/Plugins/PuzzleTokens.sketchplugin/Contents/Sketch/cmdline-functions.js:4058:22)
    at /Users/vincentk/Library/Application Support/com.bohemiancoding.sketch3/Plugins/PuzzleTokens.sketchplugin/Contents/Sketch/cmdline-functions.js:4131:36
    at value (/Applications/Sketch.app/Contents/Resources/SketchAPI_dom.js:1:32133)
    at cmdRun (/Users/vincentk/Library/Application Support/com.bohemiancoding.sketch3/Plugins/PuzzleTokens.sketchplugin/Contents/Sketch/cmdline-functions.js:4119:18){"file":"/Users/vincentk/Versions/ConnectApp/connect_app_atomic_library-vm.sketch","saveAs":"/Users/vincentk/Versions/ConnectApp/connect_app_atomic_library-sunrise.sketch","styles":"/Users/vincentk/Documents/design-assets/Sunrise/Css/Sunrise.less","commands":"apply,save,close"}

**Comment by MaxBazarov** [comment]
Fixed in 8.19.1

**Comment by vkoopmans-resoluut** [comment]
Wow at the speed of Light! 🙏

**Comment by MaxBazarov** [comment]
Sorry for the broken functionality.
I added a new feature and didn't test all functions  — my fault.

BTW, now can use new command - "Apply to existing styles". You select a file with tokes which used before to apply styles. The plugin gets token values and updates all related styles. It does it very quickly (1 min vs 15 min on my main project).  Works very will to switch between skins.

It requires this setting enabled -
<img width="594" alt="Screenshot 2022-05-18 at 00 29 13" src="https://user-images.githubusercontent.com/18418306/168913807-8f731e25-3225-43a1-b21f-147b7fab6342.png">

**Comment by vkoopmans-resoluut** [comment]
Hi Maxim!

No worries, thank your fixing PT that quick!
Let me check out the “apply to existing styles “ today!

Thanks again,

Vince

__________

**Comment by MaxBazarov** [comment]
Investigating….
